FROM jenkins/jenkins:latest

USER root

# Install required packages
RUN apt-get update && \
    apt-get install -y \
    docker.io \
    git \
    wget \
    unzip \
    python3 \
    python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    usermod -aG docker jenkins

# Install Sonar Scanner
RUN wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip && \
    unzip sonar-scanner-cli-7.3.0.5189-linux-x64.zip -d /opt && \
    mv /opt/sonar-scanner-* /opt/sonar-scanner && \
    rm sonar-scanner-cli-7.3.0.5189-linux-x64.zip

# Add Sonar Scanner to PATH
ENV PATH="/opt/sonar-scanner/bin:${PATH}"

USER jenkins

# Install Jenkins plugins
RUN jenkins-plugin-cli --plugins \
    git \
    git-client \
    workflow-aggregator \
    workflow-job \
    workflow-cps \
    pipeline-stage-view \
    docker-workflow \
    sonar