FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt-get update && \
    apt-get install -y \
    docker.io \
    git \
    wget \
    unzip \
    python3 \
    python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    usermod -aG docker jenkins && \
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip && \
    unzip sonar-scanner-cli-7.3.0.5189-linux-x64.zip -d /opt && \
    mv /opt/sonar-scanner-* /opt/sonar-scanner && \
    rm sonar-scanner-cli-7.3.0.5189-linux-x64.zip

ENV PATH="/opt/sonar-scanner/bin:${PATH}"

USER jenkins

RUN jenkins-plugin-cli --plugins \
    git \
    git-client \
    workflow-aggregator \
    docker-workflow \
    sonar
